/**
 * Tennessee State Parks trip-guide registry.
 *
 * Every TN state park has metadata here. Parks with written long-form
 * guides have `hasGuide: true` and link to the markdown in
 * content/trips/{slug}.md.
 *
 * Built incrementally — 62 parks total, guides added park-by-park.
 */

export type TripRegion = 'west' | 'middle' | 'east';

export type TripEcoregion =
  | 'mississippi-flyway'
  | 'river-bluff-lake'
  | 'western-highland-rim'
  | 'central-basin'
  | 'eastern-highland-rim'
  | 'cumberland-plateau'
  | 'ridge-and-valley'
  | 'southern-appalachian'
  | 'urban';

export type TripPriority = 1 | 2 | 3 | 4 | 5;

export interface TripGuide {
  slug: string;
  name: string;
  region: TripRegion;
  ecoregion: TripEcoregion;
  priority: TripPriority;
  county: string;
  acres: number;
  /** [lng, lat] */
  coords: [number, number];
  /** One-line habitat summary */
  habitat: string;
  /** 1–3 signature bird names for quick reference */
  signatureBirds: string[];
  /** Rough drive time from Memphis (e.g. "3 hr") */
  driveFromMemphis: string;
  /** If true, the park has a dedicated markdown trip guide */
  hasGuide: boolean;
  /** Short "why go here" tagline */
  tagline: string;
}

export const TN_STATE_PARKS: TripGuide[] = [
  // ───── WEST TN (Mississippi Flyway) ─────
  {
    slug: 'reelfoot-lake',
    name: 'Reelfoot Lake',
    region: 'west',
    ecoregion: 'mississippi-flyway',
    priority: 5,
    county: 'Lake/Obion',
    acres: 15280,
    coords: [-89.379, 36.383],
    habitat: 'Earthquake-created lake (1811–12) with cypress swamp',
    signatureBirds: ['Bald Eagle', 'American White Pelican', 'Sandhill Crane'],
    driveFromMemphis: '2 hr',
    hasGuide: true,
    tagline: 'Bald Eagle capital of Tennessee · 400+ wintering eagles',
  },
  {
    slug: 'big-hill-pond',
    name: 'Big Hill Pond',
    region: 'west',
    ecoregion: 'mississippi-flyway',
    priority: 5,
    county: 'McNairy',
    acres: 4138,
    coords: [-88.728, 35.019],
    habitat: 'Swamp forest + beaver wetlands + bottomland hardwood',
    signatureBirds: ['Prothonotary Warbler', 'Yellow-crowned Night-Heron'],
    driveFromMemphis: '1.5 hr',
    hasGuide: true,
    tagline: 'Cypress swamp birding closest to Memphis',
  },
  {
    slug: 'meeman-shelby-forest',
    name: 'Meeman-Shelby Forest',
    region: 'west',
    ecoregion: 'mississippi-flyway',
    priority: 5,
    county: 'Shelby',
    acres: 12539,
    coords: [-90.0475, 35.3295],
    habitat: 'Mississippi River bluffs + bottomland hardwood',
    signatureBirds: ['Prothonotary Warbler', 'Mississippi Kite', 'Barred Owl'],
    driveFromMemphis: '30 min',
    hasGuide: true,
    tagline: 'Memphis Big 5 — already in the main guide',
  },
  {
    slug: 't-o-fuller',
    name: 'T.O. Fuller',
    region: 'west',
    ecoregion: 'mississippi-flyway',
    priority: 3,
    county: 'Shelby',
    acres: 1138,
    coords: [-90.1233, 35.0553],
    habitat: 'Bottomland forest (Memphis metro)',
    signatureBirds: ['Barred Owl', 'Pileated Woodpecker'],
    driveFromMemphis: '20 min',
    hasGuide: true,
    tagline: 'Underbirded bottomland just south of Downtown',
  },
  {
    slug: 'big-cypress-tree',
    name: 'Big Cypress Tree',
    region: 'west',
    ecoregion: 'mississippi-flyway',
    priority: 2,
    county: 'Weakley',
    acres: 330,
    coords: [-88.616, 36.355],
    habitat: 'Bottomland · ancient cypress specimens',
    signatureBirds: ['Prothonotary Warbler'],
    driveFromMemphis: '2.5 hr',
    hasGuide: true,
    tagline: 'Small park protecting ancient cypress trees',
  },
  {
    slug: 'fort-pillow',
    name: 'Fort Pillow',
    region: 'west',
    ecoregion: 'mississippi-flyway',
    priority: 1,
    county: 'Lauderdale',
    acres: 1642,
    coords: [-89.839, 35.638],
    habitat: 'Chickasaw Bluffs · Civil War site + forest',
    signatureBirds: ['Bluff migrants'],
    driveFromMemphis: '1 hr',
    hasGuide: true,
    tagline: 'Historic site with migrant watching potential',
  },
  {
    slug: 'middle-fork-bottoms',
    name: 'Middle Fork Bottoms',
    region: 'west',
    ecoregion: 'mississippi-flyway',
    priority: 2,
    county: 'Madison',
    acres: 2300,
    coords: [-88.812, 35.658],
    habitat: 'Bottomland hardwood + Forked Deer River',
    signatureBirds: ['Swamp warblers', 'Waterfowl'],
    driveFromMemphis: '1.5 hr',
    hasGuide: true,
    tagline: 'Underexplored bottomland east of Jackson',
  },
  {
    slug: 'pinson-mounds',
    name: 'Pinson Mounds',
    region: 'west',
    ecoregion: 'mississippi-flyway',
    priority: 1,
    county: 'Madison',
    acres: 1200,
    coords: [-88.685, 35.502],
    habitat: 'Archaeological site + South Fork Forked Deer River',
    signatureBirds: ['Forest + edge species'],
    driveFromMemphis: '1.5 hr',
    hasGuide: true,
    tagline: 'Native American mounds + river corridor',
  },

  // ───── WEST TN (Kentucky Lake / river-bluff) ─────
  {
    slug: 'natchez-trace',
    name: 'Natchez Trace',
    region: 'west',
    ecoregion: 'river-bluff-lake',
    priority: 4,
    county: 'Henderson/Benton/Carroll/Humphreys',
    acres: 48000,
    coords: [-88.258, 35.807],
    habitat: "Tennessee's largest state park · 4 lakes + upland forest",
    signatureBirds: ['Bald Eagle', 'Warblers', 'Wild Turkey'],
    driveFromMemphis: '2 hr',
    hasGuide: true,
    tagline: "TN's biggest state park · 48,000 acres",
  },
  {
    slug: 'chickasaw',
    name: 'Chickasaw',
    region: 'west',
    ecoregion: 'river-bluff-lake',
    priority: 4,
    county: 'Chester',
    acres: 14400,
    coords: [-89.029, 35.404],
    habitat: 'Upland hardwood + CCC-era lakes',
    signatureBirds: ['Wood Duck', 'Pileated Woodpecker', 'Warblers'],
    driveFromMemphis: '1.5 hr',
    hasGuide: true,
    tagline: 'CCC-era lakes in west TN upland forest',
  },
  {
    slug: 'nathan-bedford-forrest',
    name: 'Nathan Bedford Forrest',
    region: 'west',
    ecoregion: 'river-bluff-lake',
    priority: 4,
    county: 'Benton',
    acres: 2587,
    coords: [-88.007, 36.094],
    habitat: 'Kentucky Lake bluffs + bottomland',
    signatureBirds: ['Bald Eagle', 'Waterfowl', 'Osprey'],
    driveFromMemphis: '2 hr',
    hasGuide: true,
    tagline: 'Kentucky Lake bluff winter eagle viewing',
  },
  {
    slug: 'paris-landing',
    name: 'Paris Landing',
    region: 'west',
    ecoregion: 'river-bluff-lake',
    priority: 4,
    county: 'Henry',
    acres: 841,
    coords: [-88.088, 36.432],
    habitat: 'Kentucky Lake peninsula',
    signatureBirds: ['Bald Eagle', 'American White Pelican', 'Waterfowl'],
    driveFromMemphis: '2.5 hr',
    hasGuide: true,
    tagline: 'Kentucky Lake waterfowl + winter pelicans',
  },
  {
    slug: 'mousetail-landing',
    name: 'Mousetail Landing',
    region: 'west',
    ecoregion: 'river-bluff-lake',
    priority: 3,
    county: 'Perry',
    acres: 1247,
    coords: [-87.982, 35.684],
    habitat: 'Tennessee River bluffs',
    signatureBirds: ['Waterfowl', 'Raptors'],
    driveFromMemphis: '3 hr',
    hasGuide: true,
    tagline: 'Remote Tennessee River bluffs',
  },
  {
    slug: 'pickwick-landing',
    name: 'Pickwick Landing',
    region: 'west',
    ecoregion: 'river-bluff-lake',
    priority: 2,
    county: 'Hardin',
    acres: 1400,
    coords: [-88.241, 35.068],
    habitat: 'Pickwick Lake · dam tailwater',
    signatureBirds: ['Waterfowl', 'Gulls'],
    driveFromMemphis: '2 hr',
    hasGuide: true,
    tagline: 'Resort park on Pickwick Lake',
  },
  {
    slug: 'johnsonville',
    name: 'Johnsonville',
    region: 'west',
    ecoregion: 'river-bluff-lake',
    priority: 2,
    county: 'Humphreys',
    acres: 636,
    coords: [-87.965, 36.057],
    habitat: 'Tennessee River · Civil War site',
    signatureBirds: ['Waterfowl', 'Riparian'],
    driveFromMemphis: '2.5 hr',
    hasGuide: true,
    tagline: 'Civil War river-battle site',
  },

  // ───── MIDDLE TN (Western Highland Rim) ─────
  {
    slug: 'montgomery-bell',
    name: 'Montgomery Bell',
    region: 'middle',
    ecoregion: 'western-highland-rim',
    priority: 5,
    county: 'Dickson',
    acres: 3782,
    coords: [-87.2784, 36.1006],
    habitat: 'Upland hardwood + hemlock ravines + streams',
    signatureBirds: ['Wood Thrush', 'Hooded Warbler', 'Louisiana Waterthrush'],
    driveFromMemphis: '3 hr',
    hasGuide: true,
    tagline: 'Upland forest targets you won\'t see in Memphis',
  },
  {
    slug: 'henry-horton',
    name: 'Henry Horton',
    region: 'middle',
    ecoregion: 'western-highland-rim',
    priority: 3,
    county: 'Marshall',
    acres: 1523,
    coords: [-86.697, 35.589],
    habitat: 'Duck River corridor + forest',
    signatureBirds: ['Belted Kingfisher', 'Riparian species'],
    driveFromMemphis: '3.5 hr',
    hasGuide: true,
    tagline: 'Duck River riparian birding',
  },
  {
    slug: 'harpeth-river',
    name: 'Harpeth River',
    region: 'middle',
    ecoregion: 'western-highland-rim',
    priority: 3,
    county: 'Cheatham/Davidson',
    acres: 750,
    coords: [-87.030, 36.190],
    habitat: 'Harpeth River corridor',
    signatureBirds: ['Belted Kingfisher', 'Louisiana Waterthrush'],
    driveFromMemphis: '3 hr',
    hasGuide: true,
    tagline: 'Riverine habitat near Nashville',
  },
  {
    slug: 'david-crockett',
    name: 'David Crockett',
    region: 'middle',
    ecoregion: 'western-highland-rim',
    priority: 3,
    county: 'Lawrence',
    acres: 1319,
    coords: [-87.344, 35.239],
    habitat: 'Shoal Creek + upland forest',
    signatureBirds: ['Summer warblers', 'Wood Thrush'],
    driveFromMemphis: '3 hr',
    hasGuide: true,
    tagline: 'Shoal Creek forest south of Nashville',
  },
  {
    slug: 'dunbar-cave',
    name: 'Dunbar Cave',
    region: 'middle',
    ecoregion: 'western-highland-rim',
    priority: 3,
    county: 'Montgomery',
    acres: 144,
    coords: [-87.302, 36.557],
    habitat: 'Karst cave + forest',
    signatureBirds: ['Chimney Swift (roosts)', 'Forest species'],
    driveFromMemphis: '3.5 hr',
    hasGuide: true,
    tagline: 'Prehistoric cave art + forest birds',
  },
  {
    slug: 'port-royal',
    name: 'Port Royal',
    region: 'middle',
    ecoregion: 'western-highland-rim',
    priority: 2,
    county: 'Montgomery/Robertson',
    acres: 34,
    coords: [-87.135, 36.565],
    habitat: 'Red River + historic town',
    signatureBirds: ['Riparian'],
    driveFromMemphis: '3.5 hr',
    hasGuide: true,
    tagline: 'Historic riverside town',
  },
  {
    slug: 'devils-backbone',
    name: "Devil's Backbone",
    region: 'middle',
    ecoregion: 'western-highland-rim',
    priority: 2,
    county: 'Lewis',
    acres: 1500,
    coords: [-87.540, 35.478],
    habitat: 'Western Highland Rim ridges · Natchez Trace',
    signatureBirds: ['Upland forest (developing)'],
    driveFromMemphis: '3 hr',
    hasGuide: true,
    tagline: "TN's newest state park · opening in stages",
  },
  {
    slug: 'old-stone-fort',
    name: 'Old Stone Fort',
    region: 'middle',
    ecoregion: 'western-highland-rim',
    priority: 1,
    county: 'Coffee',
    acres: 876,
    coords: [-86.100, 35.486],
    habitat: 'Archaeological + Duck River',
    signatureBirds: ['Riparian', 'Forest'],
    driveFromMemphis: '4 hr',
    hasGuide: true,
    tagline: '2,000-year-old Native American earthwork',
  },

  // ───── MIDDLE TN (Central Basin + cedar glade) ─────
  {
    slug: 'radnor-lake',
    name: 'Radnor Lake',
    region: 'middle',
    ecoregion: 'central-basin',
    priority: 5,
    county: 'Davidson',
    acres: 1368,
    coords: [-86.810, 36.060],
    habitat: "Nashville's premier nature area · lake + forest",
    signatureBirds: ['Bald Eagle', '240+ species recorded'],
    driveFromMemphis: '3 hr',
    hasGuide: true,
    tagline: 'Nashville\'s birding crown jewel',
  },
  {
    slug: 'cedars-of-lebanon',
    name: 'Cedars of Lebanon',
    region: 'middle',
    ecoregion: 'central-basin',
    priority: 5,
    county: 'Wilson',
    acres: 9420,
    coords: [-86.324, 36.076],
    habitat: 'Globally rare cedar glade ecosystem',
    signatureBirds: ['Prairie Warbler', 'Yellow-breasted Chat', "Chuck-will's-widow"],
    driveFromMemphis: '3.5 hr',
    hasGuide: true,
    tagline: 'Cedar glade endemic habitat',
  },
  {
    slug: 'long-hunter',
    name: 'Long Hunter',
    region: 'middle',
    ecoregion: 'central-basin',
    priority: 4,
    county: 'Davidson',
    acres: 2600,
    coords: [-86.550, 36.086],
    habitat: 'Percy Priest Lake + cedar glades',
    signatureBirds: ['Waterfowl', 'Wild Turkey'],
    driveFromMemphis: '3.5 hr',
    hasGuide: true,
    tagline: 'Percy Priest Lake winter waterfowl',
  },
  {
    slug: 'bledsoe-creek',
    name: 'Bledsoe Creek',
    region: 'middle',
    ecoregion: 'central-basin',
    priority: 3,
    county: 'Sumner',
    acres: 164,
    coords: [-86.377, 36.376],
    habitat: 'Old Hickory Lake inlet',
    signatureBirds: ['Winter waterfowl'],
    driveFromMemphis: '3.5 hr',
    hasGuide: true,
    tagline: 'Small Old Hickory Lake inlet',
  },
  {
    slug: 'bicentennial-capitol-mall',
    name: 'Bicentennial Capitol Mall',
    region: 'middle',
    ecoregion: 'urban',
    priority: 2,
    county: 'Davidson',
    acres: 19,
    coords: [-86.784, 36.170],
    habitat: 'Urban Nashville · fountains + lawns',
    signatureBirds: ['Urban species'],
    driveFromMemphis: '3 hr',
    hasGuide: true,
    tagline: 'Urban Nashville state park',
  },

  // ───── MIDDLE TN (Eastern Highland Rim — plateau transition) ─────
  {
    slug: 'burgess-falls',
    name: 'Burgess Falls',
    region: 'middle',
    ecoregion: 'eastern-highland-rim',
    priority: 3,
    county: 'Putnam',
    acres: 350,
    coords: [-85.592, 36.093],
    habitat: 'Dramatic waterfalls + gorge',
    signatureBirds: ['Louisiana Waterthrush', 'Black-throated Green'],
    driveFromMemphis: '4 hr',
    hasGuide: true,
    tagline: 'Four-tier waterfall cascade',
  },
  {
    slug: 'tims-ford',
    name: 'Tims Ford',
    region: 'middle',
    ecoregion: 'eastern-highland-rim',
    priority: 3,
    county: 'Franklin',
    acres: 3546,
    coords: [-86.202, 35.259],
    habitat: 'Tims Ford Lake',
    signatureBirds: ['Bald Eagle', 'Waterfowl'],
    driveFromMemphis: '4 hr',
    hasGuide: true,
    tagline: 'Tims Ford Lake reservoir',
  },
  {
    slug: 'edgar-evins',
    name: 'Edgar Evins',
    region: 'middle',
    ecoregion: 'eastern-highland-rim',
    priority: 3,
    county: 'DeKalb',
    acres: 6300,
    coords: [-85.829, 36.085],
    habitat: 'Center Hill Lake',
    signatureBirds: ['Osprey', 'Waterfowl'],
    driveFromMemphis: '4.5 hr',
    hasGuide: true,
    tagline: 'Center Hill Lake uplands',
  },
  {
    slug: 'cummins-falls',
    name: 'Cummins Falls',
    region: 'middle',
    ecoregion: 'eastern-highland-rim',
    priority: 3,
    county: 'Jackson',
    acres: 282,
    coords: [-85.573, 36.285],
    habitat: 'Plateau waterfall + gorge',
    signatureBirds: ['Louisiana Waterthrush', 'Warblers'],
    driveFromMemphis: '4.5 hr',
    hasGuide: true,
    tagline: '75-ft waterfall swimming hole',
  },
  {
    slug: 'rock-island',
    name: 'Rock Island',
    region: 'middle',
    ecoregion: 'eastern-highland-rim',
    priority: 3,
    county: 'Warren/White',
    acres: 883,
    coords: [-85.644, 35.830],
    habitat: 'Caney Fork River confluence',
    signatureBirds: ['Winter waterfowl', 'Herons'],
    driveFromMemphis: '4.5 hr',
    hasGuide: true,
    tagline: 'Caney Fork & Collins River confluence',
  },
  {
    slug: 'standing-stone',
    name: 'Standing Stone',
    region: 'middle',
    ecoregion: 'eastern-highland-rim',
    priority: 3,
    county: 'Overton',
    acres: 11000,
    coords: [-85.423, 36.468],
    habitat: 'Plateau transition · forest + lake',
    signatureBirds: ['Breeding warblers', 'Wild Turkey'],
    driveFromMemphis: '5 hr',
    hasGuide: true,
    tagline: 'Large CCC-built plateau park',
  },
  {
    slug: 'cordell-hull-birthplace',
    name: 'Cordell Hull Birthplace',
    region: 'middle',
    ecoregion: 'eastern-highland-rim',
    priority: 3,
    county: 'Pickett',
    acres: 59,
    coords: [-85.068, 36.508],
    habitat: 'Plateau forest · historic site',
    signatureBirds: ['Forest species'],
    driveFromMemphis: '5.5 hr',
    hasGuide: true,
    tagline: 'Birthplace of Nobel Peace laureate',
  },
  {
    slug: 'sgt-alvin-c-york',
    name: 'Sgt. Alvin C. York',
    region: 'middle',
    ecoregion: 'eastern-highland-rim',
    priority: 1,
    county: 'Fentress',
    acres: 36,
    coords: [-84.805, 36.407],
    habitat: 'WWI hero homestead',
    signatureBirds: ['Open-country species'],
    driveFromMemphis: '6 hr',
    hasGuide: true,
    tagline: 'WWI Medal of Honor site',
  },
  {
    slug: 'david-crockett-birthplace',
    name: 'David Crockett Birthplace',
    region: 'middle',
    ecoregion: 'eastern-highland-rim',
    priority: 1,
    county: 'Greene',
    acres: 105,
    coords: [-82.655, 36.211],
    habitat: 'Nolichucky River · historic',
    signatureBirds: ['Riparian'],
    driveFromMemphis: '7 hr',
    hasGuide: true,
    tagline: "Davy Crockett's birthplace on the river",
  },

  // ───── EAST TN (Cumberland Plateau) ─────
  {
    slug: 'fall-creek-falls',
    name: 'Fall Creek Falls',
    region: 'east',
    ecoregion: 'cumberland-plateau',
    priority: 5,
    county: 'Van Buren/Bledsoe',
    acres: 26000,
    coords: [-85.349, 35.664],
    habitat: 'Plateau + waterfalls + deep gorges',
    signatureBirds: ['Cerulean Warbler', 'Worm-eating', 'Louisiana Waterthrush'],
    driveFromMemphis: '5 hr',
    hasGuide: true,
    tagline: "TN's crown jewel state park · 256-ft waterfall",
  },
  {
    slug: 'frozen-head',
    name: 'Frozen Head',
    region: 'east',
    ecoregion: 'cumberland-plateau',
    priority: 5,
    county: 'Morgan',
    acres: 24000,
    coords: [-84.507, 36.128],
    habitat: 'Old-growth cove forest · highest Cumberland peak',
    signatureBirds: ['Black-throated Blue', 'Canada Warbler', 'Golden-winged'],
    driveFromMemphis: '6 hr',
    hasGuide: true,
    tagline: 'Old-growth cove forest · 3,300 ft elevation',
  },
  {
    slug: 'pickett-ccc',
    name: 'Pickett CCC Memorial',
    region: 'east',
    ecoregion: 'cumberland-plateau',
    priority: 4,
    county: 'Pickett',
    acres: 19200,
    coords: [-84.798, 36.537],
    habitat: 'Plateau transition · old-growth pockets',
    signatureBirds: ['Cerulean Warbler', 'Pileated', 'Black-throated Green'],
    driveFromMemphis: '6 hr',
    hasGuide: true,
    tagline: 'Remote plateau forest + natural bridges',
  },
  {
    slug: 'south-cumberland',
    name: 'South Cumberland',
    region: 'east',
    ecoregion: 'cumberland-plateau',
    priority: 4,
    county: 'Franklin/Marion/Grundy',
    acres: 30000,
    coords: [-85.627, 35.270],
    habitat: 'Plateau complex (includes Savage Gulf)',
    signatureBirds: ['Cerulean', "Swainson's Warbler", 'Louisiana Waterthrush'],
    driveFromMemphis: '5.5 hr',
    hasGuide: true,
    tagline: '30,000-acre plateau wilderness complex',
  },
  {
    slug: 'savage-gulf',
    name: 'Savage Gulf',
    region: 'east',
    ecoregion: 'cumberland-plateau',
    priority: 4,
    county: 'Grundy/Sequatchie',
    acres: 15500,
    coords: [-85.531, 35.410],
    habitat: 'Deepest gorges on the plateau',
    signatureBirds: ['Cerulean', 'Black-throated Blue', 'Warblers'],
    driveFromMemphis: '5 hr',
    hasGuide: true,
    tagline: "Deepest gorges on TN's Cumberland Plateau",
  },
  {
    slug: 'cumberland-mountain',
    name: 'Cumberland Mountain',
    region: 'east',
    ecoregion: 'cumberland-plateau',
    priority: 4,
    county: 'Cumberland',
    acres: 1720,
    coords: [-84.993, 35.897],
    habitat: 'CCC-built park · plateau forest',
    signatureBirds: ['Warblers', 'Ruffed Grouse (historic)'],
    driveFromMemphis: '5 hr',
    hasGuide: true,
    tagline: 'Historic CCC architecture + plateau',
  },
  {
    slug: 'scotts-gulf',
    name: "Scott's Gulf Wilderness",
    region: 'east',
    ecoregion: 'cumberland-plateau',
    priority: 3,
    county: 'White',
    acres: 10000,
    coords: [-85.333, 35.800],
    habitat: 'Caney Fork canyons',
    signatureBirds: ['Cerulean', 'Louisiana Waterthrush'],
    driveFromMemphis: '5 hr',
    hasGuide: true,
    tagline: 'Remote canyon wilderness',
  },
  {
    slug: 'north-chickamauga-creek-gorge',
    name: 'North Chickamauga Creek Gorge',
    region: 'east',
    ecoregion: 'cumberland-plateau',
    priority: 3,
    county: 'Hamilton',
    acres: 7000,
    coords: [-85.185, 35.259],
    habitat: 'Plateau gorge',
    signatureBirds: ['Cerulean', 'Worm-eating'],
    driveFromMemphis: '5.5 hr',
    hasGuide: true,
    tagline: 'Gorge north of Chattanooga',
  },
  {
    slug: 'justin-p-wilson-cumberland-trail',
    name: 'Justin P. Wilson Cumberland Trail',
    region: 'east',
    ecoregion: 'cumberland-plateau',
    priority: 3,
    county: 'Multiple',
    acres: 31500,
    coords: [-85.000, 36.000],
    habitat: 'Long-distance trail corridor',
    signatureBirds: ['Varies by section'],
    driveFromMemphis: 'Varies',
    hasGuide: true,
    tagline: '300-mile trail across the plateau',
  },

  // ───── EAST TN (Ridge & Valley — Norris/Douglas/Cherokee lakes) ─────
  {
    slug: 'norris-dam',
    name: 'Norris Dam',
    region: 'east',
    ecoregion: 'ridge-and-valley',
    priority: 4,
    county: 'Anderson/Campbell',
    acres: 4000,
    coords: [-84.088, 36.220],
    habitat: 'Norris Lake + Clinch River',
    signatureBirds: ['Bald Eagle', 'Cerulean Warbler'],
    driveFromMemphis: '6.5 hr',
    hasGuide: true,
    tagline: 'First TVA dam · lake + river forest',
  },
  {
    slug: 'big-ridge',
    name: 'Big Ridge',
    region: 'east',
    ecoregion: 'ridge-and-valley',
    priority: 3,
    county: 'Union',
    acres: 3687,
    coords: [-83.935, 36.243],
    habitat: 'Norris Lake + ridge/valley',
    signatureBirds: ['Waterfowl', 'Forest'],
    driveFromMemphis: '7 hr',
    hasGuide: true,
    tagline: 'CCC-era Norris Lake park',
  },
  {
    slug: 'cove-lake',
    name: 'Cove Lake',
    region: 'east',
    ecoregion: 'ridge-and-valley',
    priority: 3,
    county: 'Campbell',
    acres: 673,
    coords: [-84.142, 36.390],
    habitat: 'Small lake + mountain foothills',
    signatureBirds: ['Waterfowl', 'Woodpeckers'],
    driveFromMemphis: '7 hr',
    hasGuide: true,
    tagline: 'Small lake at foot of Cumberland Mtns',
  },
  {
    slug: 'panther-creek',
    name: 'Panther Creek',
    region: 'east',
    ecoregion: 'ridge-and-valley',
    priority: 3,
    county: 'Hamblen',
    acres: 1435,
    coords: [-83.411, 36.187],
    habitat: 'Cherokee Lake · ridge/valley',
    signatureBirds: ['Waterfowl', 'Bald Eagle'],
    driveFromMemphis: '7.5 hr',
    hasGuide: true,
    tagline: 'Cherokee Lake ridge park',
  },
  {
    slug: 'warriors-path',
    name: "Warriors' Path",
    region: 'east',
    ecoregion: 'ridge-and-valley',
    priority: 4,
    county: 'Sullivan',
    acres: 950,
    coords: [-82.493, 36.511],
    habitat: 'Boone Lake + ridge forest',
    signatureBirds: ['Eastern breeders', 'Lake waterfowl'],
    driveFromMemphis: '8 hr',
    hasGuide: true,
    tagline: 'Kingsport-area lake + trails',
  },
  {
    slug: 'harrison-bay',
    name: 'Harrison Bay',
    region: 'east',
    ecoregion: 'ridge-and-valley',
    priority: 4,
    county: 'Hamilton',
    acres: 1200,
    coords: [-85.119, 35.180],
    habitat: 'Chickamauga Lake',
    signatureBirds: ['Bald Eagle', 'Waterfowl', 'Osprey'],
    driveFromMemphis: '6 hr',
    hasGuide: true,
    tagline: 'Bald Eagle Cam park on Chickamauga Lake',
  },
  {
    slug: 'booker-t-washington',
    name: 'Booker T. Washington',
    region: 'east',
    ecoregion: 'ridge-and-valley',
    priority: 3,
    county: 'Hamilton',
    acres: 353,
    coords: [-85.101, 35.113],
    habitat: 'Chickamauga Lake + forest edge',
    signatureBirds: ['Waterfowl', 'Forest edge'],
    driveFromMemphis: '6 hr',
    hasGuide: true,
    tagline: 'Historic Chattanooga-area park',
  },
  {
    slug: 'indian-mountain',
    name: 'Indian Mountain',
    region: 'east',
    ecoregion: 'ridge-and-valley',
    priority: 2,
    county: 'Campbell',
    acres: 213,
    coords: [-84.155, 36.582],
    habitat: 'Small ridge + lake',
    signatureBirds: ['Forest + lake'],
    driveFromMemphis: '7 hr',
    hasGuide: true,
    tagline: 'Small park at KY border',
  },
  {
    slug: 'fort-loudoun',
    name: 'Fort Loudoun',
    region: 'east',
    ecoregion: 'ridge-and-valley',
    priority: 1,
    county: 'Monroe',
    acres: 1200,
    coords: [-84.204, 35.591],
    habitat: 'Historic fort · Tellico Lake',
    signatureBirds: ['Waterfowl'],
    driveFromMemphis: '6.5 hr',
    hasGuide: true,
    tagline: '18th-century British fort reconstruction',
  },
  {
    slug: 'red-clay',
    name: 'Red Clay',
    region: 'east',
    ecoregion: 'ridge-and-valley',
    priority: 3,
    county: 'Bradley',
    acres: 263,
    coords: [-84.935, 35.015],
    habitat: 'Cherokee historic site + woodland',
    signatureBirds: ['Open-country + forest'],
    driveFromMemphis: '6 hr',
    hasGuide: true,
    tagline: 'Cherokee Nation council grounds',
  },

  // ───── EAST TN (Southern Appalachian) ─────
  {
    slug: 'roan-mountain',
    name: 'Roan Mountain',
    region: 'east',
    ecoregion: 'southern-appalachian',
    priority: 5,
    county: 'Carter',
    acres: 2006,
    coords: [-82.092, 36.144],
    habitat: 'High-elevation spruce-fir + rhododendron bald',
    signatureBirds: ['Breeding Dark-eyed Junco', 'Canada Warbler', 'Winter Wren'],
    driveFromMemphis: '8 hr',
    hasGuide: true,
    tagline: 'Breeding boreal birds at 6,285 ft',
  },
  {
    slug: 'rocky-fork',
    name: 'Rocky Fork',
    region: 'east',
    ecoregion: 'southern-appalachian',
    priority: 4,
    county: 'Unicoi',
    acres: 2000,
    coords: [-82.606, 36.060],
    habitat: 'Southern Appalachian ridges',
    signatureBirds: ['Ruffed Grouse', 'High-elevation warblers'],
    driveFromMemphis: '8 hr',
    hasGuide: true,
    tagline: 'Remote S. Appalachian wilderness',
  },
  {
    slug: 'hiwassee',
    name: 'Hiwassee Scenic River',
    region: 'east',
    ecoregion: 'southern-appalachian',
    priority: 3,
    county: 'Polk',
    acres: 500,
    coords: [-84.481, 35.163],
    habitat: 'Scenic river · Appalachian foothills',
    signatureBirds: ['Louisiana Waterthrush', 'Waterfowl'],
    driveFromMemphis: '6.5 hr',
    hasGuide: true,
    tagline: 'Clear mountain river + Sandhill Crane refuge nearby',
  },
  {
    slug: 'ocoee-river',
    name: 'Ocoee River',
    region: 'east',
    ecoregion: 'southern-appalachian',
    priority: 3,
    county: 'Polk',
    acres: 1000,
    coords: [-84.529, 35.070],
    habitat: 'Whitewater river corridor',
    signatureBirds: ['Riparian'],
    driveFromMemphis: '7 hr',
    hasGuide: true,
    tagline: "TN's newest state park (2025)",
  },
  {
    slug: 'sycamore-shoals',
    name: 'Sycamore Shoals',
    region: 'east',
    ecoregion: 'southern-appalachian',
    priority: 1,
    county: 'Carter',
    acres: 70,
    coords: [-82.269, 36.343],
    habitat: 'Watauga River · historic frontier site',
    signatureBirds: ['Riparian'],
    driveFromMemphis: '8 hr',
    hasGuide: true,
    tagline: 'Frontier history on the Watauga',
  },

  // ───── EAST TN (Knoxville specialty) ─────
  {
    slug: 'seven-islands-birding-park',
    name: 'Seven Islands State Birding Park',
    region: 'east',
    ecoregion: 'ridge-and-valley',
    priority: 5,
    county: 'Knox',
    acres: 416,
    coords: [-83.648, 35.949],
    habitat: 'French Broad River + grassland',
    signatureBirds: ["Bell's Vireo", 'Grassland sparrows', '190+ species'],
    driveFromMemphis: '6 hr',
    hasGuide: true,
    tagline: "TN's only park officially designated for birding",
  },
];

// ──────────────────────────────────────────────────────────────────────────────
// Region + ecoregion labels for UI display

export const REGION_LABELS: Record<TripRegion, string> = {
  west: 'West Tennessee',
  middle: 'Middle Tennessee',
  east: 'East Tennessee',
};

export const ECOREGION_LABELS: Record<TripEcoregion, string> = {
  'mississippi-flyway': 'Mississippi Flyway',
  'river-bluff-lake': 'River Bluffs & Lakes',
  'western-highland-rim': 'Western Highland Rim',
  'central-basin': 'Central Basin · Cedar Glades',
  'eastern-highland-rim': 'Eastern Highland Rim',
  'cumberland-plateau': 'Cumberland Plateau',
  'ridge-and-valley': 'Ridge & Valley',
  'southern-appalachian': 'Southern Appalachian',
  urban: 'Urban',
};

// ──────────────────────────────────────────────────────────────────────────────
// Query helpers

export function getTripBySlug(slug: string): TripGuide | undefined {
  return TN_STATE_PARKS.find((p) => p.slug === slug);
}

export function getTripsByRegion(region: TripRegion): TripGuide[] {
  return TN_STATE_PARKS.filter((p) => p.region === region);
}

export function getTripsByEcoregion(ecoregion: TripEcoregion): TripGuide[] {
  return TN_STATE_PARKS.filter((p) => p.ecoregion === ecoregion);
}

export function getTopPriorityTrips(minPriority: TripPriority = 4): TripGuide[] {
  return TN_STATE_PARKS.filter((p) => p.priority >= minPriority).sort(
    (a, b) => b.priority - a.priority || a.name.localeCompare(b.name),
  );
}

export function getTripsWithGuides(): TripGuide[] {
  return TN_STATE_PARKS.filter((p) => p.hasGuide);
}
